### ISSUE TITLE
MBP A1502, OSX10.15.7, do not work

### ISSUE THREAD

**Issue by XanderXu1998** [PassionPenguin/SidecarCorePatch#1]
macbook pro A1502, OSX 10.15.7
iPad air4, iPadOS 14.3

When I finish the process in Readme.md and reboot, I found my safari,Chrome and Apple Store all can not open.

What's more, I can open Sidecar but it doesn't find my iPad, which is near my MacBook and connect to the same wifi and Apple ID.

The error informations show below:

<img width="993" alt="LWScreenShot 2021-01-28 at 11 10 52" src="https://user-images.githubusercontent.com/23695541/106087700-794fea80-615f-11eb-82eb-73ed703cb56f.png">
<img width="996" alt="LWScreenShot 2021-01-28 at 11 10 43" src="https://user-images.githubusercontent.com/23695541/106087702-79e88100-615f-11eb-99ac-154d196ebf05.png">

<img width="985" alt="LWScreenShot 2021-01-28 at 11 11 03" src="https://user-images.githubusercontent.com/23695541/106087686-748b3680-615f-11eb-9d56-4374ed36ccf1.png">

**Comment by PassionPenguin** [comment]
说实在的这个只是个fork（

我按照我catalina的一些经验为你回答一下吧：

1. 先建议将备份复原
2. 预估 Apple 将 SidecarCore 框架修改了，应用 Patch 以后出现错误
3. 这个项目已经很久没有更新了，我本人成功的版本是 Catalina 最初的 beta 测试版
4. 找不到 iPad 问题，这个纯属撞运气，看情况，一旦第一次连接到了，后续可以很方便找到设备的，毕竟不是原生支持
5. 我的设备是 Macbook Pro Early 2015 A1502，iPad Air 2

**Comment by PassionPenguin** [comment]
而原 fork 也已经断更挺久的了，目前似乎有个通用解决方案是用 terminal，修改 apple defaults 的布尔值设定就可以启用了，也是撞 rp 的行为。

实在不建议启用 Sidecar，在我的 MacBook Pro 上表现极差，画质极低且抖动、延迟，似乎完全 Useless。后续设备支持 Sidecar 主要还是硬件上有所支持。

建议还是购置新的设备去体验相关的功能，我自己最后也放弃了，目前安安分分的连接 external hdmi display 去工作，也不错。
